baseurl = "https://blog.maheswaranm.com/"
title = "Just Another Developer Blog"
languageCode = "en-us"
MetaDataFormat = "toml"
paginate = 10

[author]
    name = "Maheswaran Moothiringode"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "posts/:year/:month/:day/:title/"

[params]
    mainURL = "https://maheswaranm.com"
    tagline = "Changelog of the project Maheswaran!"

    github = "http://github.com/maheswaranm"
    twitter = "http://twitter.com/maheswaranm"
    linkedin = "http://linkedin.com/in/maheswaranm"

    rss = true
